### ISSUE TITLE
If methode "setScripts" necessary?

### ISSUE THREAD

**Issue by zonky2** [postyou/metamodels-single-ce#2]
https://github.com/postyou/metamodels-single-ce/blob/master/elements/SingleElement.php#L19-L53

**Comment by garyee** [comment]
Oups, that's js- code for a specific project.... it does not belong here, but this creates the question where code like this should go...

**Comment by zonky2** [comment]
hops & wech! ;-)

**Comment by zonky2** [comment]
done https://github.com/postyou/metamodels-single-ce/commit/d69d853dba900d4e3acfaed4691c8fc32e7b3ea1
